### PR TITLE
Adding less loader

### PR DESCRIPTION
**Pull request by iFlameing**
@tiberiuichim can you comment on what I am missing in this pr? I just want to style the elements of the form builder.

### CODE REVIEW

**Comment by tiberiuichim** [comment]
To use less files, you don't need anything extra. The globals.less is not needed, the `@addon*` declarations are not needed in form-builder.less.

The `@addon*` lines will declare two variables. In globals.less we have two mixins, loadAddonVariables and loadAddonOverrides. Just like Pastanaga is customizable by Volto projects, these mixins would allow Volto projects to customize variables that you set in your addon.

**Comment by tiberiuichim** [comment]
A note though: you should call the mixins in the forms-builder.less file. You should read the semantic-ui-less code to understand it, the system it's used here mimics what Volto does.

**Comment by tisto** [comment]
@iFlameing can we close this one now that the other PR is merged?

**Comment by iFlameing** [comment]
Yes! We can close this now.

**Pull request closed without merging**
